apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ansible-deployment
spec:
  selector:
    matchLabels:
      app: ansible-devops-project
  replicas: 2 # tells deployment to run 2 pods matching the template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: ansible-devops-project
    spec:
      containers:
      - name: ansible-devops-project
        image: sforcloud/simple-devops-image
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
